window.DND_DATA = {
  heroes: [
    ['kael','Kael Ironwall','The Dragon Guardian','Dragonborn','Paladin','Proud dragon-like warriors known for their strength, honor, and courage.','Holy warriors who protect others through courage, discipline, and divine power.','Kael served as captain of the royal guard until his king sacrificed himself to save innocent lives. Since that day, Kael has wandered the world protecting those who cannot defend themselves. Although intimidating in appearance, he is patient, compassionate, and impossible to corrupt.',[4,2,5,2,4],6,'Honor-Bound — He cannot ignore someone sincerely asking for help.','Guardian — Jump in front of an attack meant for an ally.','Longsword, Shield, Chain Mail, Healing Potion'],
    ['lyra','Lyra Nightshade','The Silent Huntress','Elf','Ranger','Graceful forest dwellers with exceptional senses and unmatched agility.','Expert hunters, scouts, and survivalists.','Raised deep within Whisperwood Forest, Lyra became one of the finest trackers her people had ever seen. After losing her home to a mysterious beast, she now hunts dangerous creatures before they threaten innocent lives.',[2,5,2,3,2],5,'Claustrophobic — Tight spaces make her nervous.','Deadeye — Automatically land one perfect ranged attack.','Longbow, Hunting Knife, Rope, Binoculars'],
    ['brom','Brom Stonebeard','The Mountain Priest','Dwarf','Cleric','Hardy mountain folk famous for resilience and loyalty.','Divine healers and protectors blessed by sacred powers.','Brom spent decades serving a mountain village before leaving to spread hope beyond its borders. He believes every stranger deserves compassion and every journey should leave the world a little better.',[3,1,5,4,3],6,'Bad Knees — Long climbs are exhausting.','Divine Blessing — Fully heal one ally.','War Hammer, Holy Symbol, Healing Kit, Torch'],
    ['finn','Finn Quickfoot','The Lucky Thief','Halfling','Rogue','Small adventurers blessed with incredible luck.','Masters of stealth, traps, and infiltration.','Finn survived by stealing from the rich without ever getting caught. He has escaped prisons, noble estates, and more than one angry dragon purely through luck and quick thinking.',[1,5,2,1,4],4,'Shiny Objects — Finds valuable items difficult to ignore.','Lucky Escape — Escape almost any dangerous situation instantly.','Daggers, Lockpick Set, Rope, Smoke Bomb'],
    ['ragnar','Ragnar Bloodfist','The Berserker','Half-Orc','Barbarian','Powerful warriors driven by determination and raw strength.','Fearless fighters who unleash unstoppable fury.','Ragnar believes every challenge exists to make him stronger. He lives for battle, but deeply respects worthy opponents and protects those who earn his trust.',[5,3,4,0,2],6,'Short Temper — Insults are difficult to ignore.','Rage — Ignore pain and greatly increase your strength.','Greataxe, Throwing Axe, Fur Armor, Rations'],
    ['cedric','Cedric Vale','The Veteran Knight','Human','Fighter','Adaptable people capable of mastering almost any profession.','Disciplined warriors trained for every kind of combat.','Cedric has survived countless wars and now fights to ensure younger generations never experience what he did. His calm leadership often holds the group together.',[4,3,4,0,4],6,'Old Injury — His leg sometimes slows him down.','Second Wind — Instantly recover from a serious injury.','Sword, Shield, Plate Armor, Grappling Hook'],
    ['pip','Pip Gearspark','The Arcane Inventor','Gnome','Wizard','Inventive thinkers fascinated by discovery.','Masters of learned magic and ancient knowledge.','Pip approaches every problem like a puzzle waiting to be solved. His inventions are unpredictable, but his magical knowledge has saved more lives than anyone can count.',[1,3,1,5,3],4,'Absent-Minded — Frequently forgets where he left things.','Arcane Insight — Instantly understand a magical object or spell.','Spellbook, Wand, Magnifying Glass, Notebook'],
    ['selene','Selene Starwind','The Wandering Minstrel','Half-Elf','Bard','Naturally charming travelers who bridge many cultures.','Musicians whose words inspire and influence others.','Selene travels from kingdom to kingdom collecting stories worth remembering. She believes every stranger hides an unforgettable tale.',[2,3,2,4,5],5,'Show-Off — Loves attention a little too much.','Inspiring Anthem — Every ally gains confidence and courage.','Lute, Dagger, Journal, Traveler’s Pack'],
    ['taro','Taro Ashstep','The Wandering Disciple','Human','Monk','Versatile adventurers capable of adapting to any challenge.','Martial artists who master body and mind.','Taro left his secluded monastery seeking wisdom beyond its walls. He values discipline, patience, and peaceful solutions whenever possible.',[3,5,3,1,3],5,'Pacifist — Dislikes unnecessary violence.','Flurry Strike — Deliver a rapid combination of attacks.','Bo Staff, Travel Cloak, Rope, Waterskin'],
    ['mordren','Mordren Vale','The Cursed Scholar','Tiefling','Warlock','People touched by infernal ancestry and mysterious powers.','Spellcasters who gain magic through supernatural pacts.','Mordren traded everything for forbidden knowledge. Now he searches the world hoping to discover a way to break the pact that granted him incredible power.',[1,2,2,5,3],4,'Haunted — Occasionally hears whispers no one else can hear.','Eldritch Blast — Fire a devastating beam of magical energy.','Ancient Tome, Staff, Dark Cloak, Lantern'],
    ['aurelia','Aurelia Dawn','The Lightbearer','Aasimar','Sorcerer','People born with a mysterious celestial blessing.','Natural spellcasters whose magic comes from within.','Since childhood, Aurelia’s emotions have manifested as brilliant bursts of light. She now travels to understand the true origin of her extraordinary gift.',[1,3,2,5,4],4,'Overconfident — Sometimes trusts her magic too much.','Radiant Burst — Blind nearby enemies with brilliant light.','Magic Focus, Cloak, Healing Potion, Journal'],
    ['bran','Bran Mosscloak','The Forest Keeper','Firbolg','Druid','Gentle forest giants deeply connected to nature.','Protectors of wildlife who wield the power of nature.','Bran spent centuries protecting an ancient forest untouched by civilization. Now he travels beyond its borders to defend nature wherever it is threatened.',[4,2,4,4,2],6,'Fire Anxiety — Open flames make him uneasy.','Living Forest — Summon roots and vines to restrain enemies or protect allies.','Wooden Staff, Herbal Kit, Rope, Waterskin'],
    ['vex','Vex Coppergear','The Gadgeteer','Rock Gnome','Artificer','Ingenious inventors who solve problems with machines and creativity.','Engineers who combine technology with magic.','Vex is always building something new. Some inventions fail spectacularly, but the successful ones have saved entire expeditions from disaster.',[2,3,3,4,3],5,'Curiosity — Cannot resist pressing mysterious buttons or pulling strange levers.','Emergency Gadget — Produce the perfect tool for the current problem.','Toolkit, Mechanical Companion, Wrench, Goggles'],
    ['nyx','Nyx Shadowclaw','The Treasure Hunter','Tabaxi','Rogue','Curious feline wanderers driven by exploration.','Experts at infiltration, treasure hunting, and escaping danger.','Nyx has spent years searching forgotten ruins for legendary relics. Every map hides a secret, and every locked door is simply an invitation.',[2,5,2,1,3],4,'Treasure Fever — Rare artifacts are almost impossible to ignore.','Shadowstep — Instantly disappear into the shadows and reappear nearby.','Twin Daggers, Climbing Rope, Lockpicks, Grappling Hook'],
    ['seraph','Seraph Frostborn','The Frost Caller','Ice Genasi','Sorcerer','Elemental beings whose souls are tied to ice and winter.','Innate spellcasters capable of extraordinary elemental magic.','Born during the harshest winter in living memory, Seraph learned to embrace the cold instead of fearing it. Calm and composed, they believe patience is the greatest strength of all.',[1,3,3,5,2],5,'Heat Sensitive — Hot environments weaken concentration and magical control.','Frozen Prison — Trap an enemy in magical ice for one turn.','Ice Staff, Crystal Focus, Warm Cloak, Spellbook']
  ],
  monsters: [
    ['Giant Rat',1,'Small but aggressive rodents that attack in packs when cornered.','Swarm — If another Giant Rat is nearby, both gain one extra attack this turn.'],['Bat',1,'Fast flying creatures that live in caves and abandoned ruins.','Screech — Distracts a hero, making their next action more difficult.'],['Green Slime',1,'A slow blob of acidic slime that dissolves almost anything it touches.','Split — When defeated, it has a chance to divide into two smaller slimes with 1 Heart each.'],['Goblin',2,'Small, mischievous raiders that rely on numbers rather than strength.','Coward’s Escape — If badly hurt, immediately attempts to flee or hide.'],['Skeleton Warrior',2,'Animated bones held together by dark magic.','Bone Throw — Launches one of its own bones as a ranged attack.'],['Wolf',3,'A fast predator that hunts with its pack.','Pack Hunter — Deals extra damage if another wolf is nearby.'],['Bandit',3,'Outlaws who ambush travelers for gold and supplies.','Dirty Trick — Throws sand or dirt to distract a hero before attacking.'],['Giant Spider',3,'Massive spiders that weave deadly webs in dark places.','Web Shot — Temporarily traps a hero until they break free.'],['Orc Warrior',4,'Brutal fighters who believe strength earns respect.','War Cry — Becomes stronger after taking damage.'],['Zombie',4,'Slow undead that refuse to stay down.','Relentless — Once defeated, roll a D20. On 16+, it rises with 1 Heart remaining.'],['Kobold Captain',4,'A clever reptilian leader who commands weaker kobolds.','Command! — One nearby ally immediately takes another action.'],['Wild Boar',4,'A territorial beast that charges anything entering its territory.','Charge — Rushes forward, knocking heroes backwards.'],['Ogre',6,'Enormous giants that solve nearly every problem with brute force.','Ground Smash — Everyone standing nearby risks taking damage.'],['Troll',6,'Regenerating monsters famous for incredible toughness.','Regenerate — Recover 1 Heart at the beginning of every turn unless recently burned by fire.'],['Mimic',5,'A magical creature disguised as an ordinary treasure chest.','Sticky Bite — The first hero who opens it becomes temporarily stuck.'],['Werewolf',6,'A savage creature that shifts between human and wolf.','Moon Frenzy — When badly wounded, immediately gains an extra attack.'],['Necromancer',7,'A dark spellcaster who commands the dead.','Raise Dead — Bring back one defeated Skeleton or Zombie with 2 Hearts.'],['Stone Golem',8,'An ancient magical guardian carved entirely from stone.','Unbreakable — Ignore the first damage taken each battle.'],['Forest Guardian',7,'An enormous spirit created to protect sacred forests.','Nature’s Wrath — Summon roots and vines to restrain every nearby hero.'],['Young Dragon',10,'A young dragon already powerful enough to devastate entire villages.','Dragon Breath — Unleash a devastating elemental attack affecting every hero caught in front of it.']
  ]
};
